version: "3"
services:
  lighthouse:
    cap_add:
      - SYS_ADMIN
    build:
      context: ./docker/lighthousebot/
    ports:
      - 8080:8080
  app:
    build: .
    volumes:
      - ./:/myapp
    environment:
      - WEBPACKER_DEV_SERVER_HOST=0.0.0.0
    ports:
      - 3000:3000
      - 3035:3035
    depends_on:
      - db
  db:
    image: postgres:12-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD:123456
    ports:
      - 15432:5432
    restart: always
volumes:
  pgdata:
